---
title: "DebarcodeR Example"
author: "Benjamin Reisman and Sierra Barone"
date: "03/16/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load libraries and read in data

Load flowCore, tidyverse, and debarcoder packages. Read in FCS files for the stained sample and the uptake control sample

```{r setup}

# load libraries
library(flowCore)
library(debarcoder)
library(tidyverse)
library(ggplot2)

# read in FCS files for barcoded and uptake control samples
barcoded.ff <- read.FCS("stained.fcs")
uptake.ff <- read.FCS("uptake.fcs")

myplatemap <- tibble(`Pacific Blue-A` = rep(1:8, times = 6), 
       `Pacific Orange-A` = rep(1:6, each = 8)) %>%
  mutate(well = paste0(LETTERS[`Pacific Blue-A`], "0", `Pacific Orange-A`))
```

# Deskew barcoding channel using a regression method

Deskew each barcoding channel individually choosing predictors, method, and channel

```{r minimal parallel workflow}
##------------------------------------------------------------------------------
barcoded.ff <- deskew_fcbFlowFrame(barcoded.ff, ret.model = T, predictors = c("fsc_a","ssc_a"),# "fsc_h", "fsc_w", "ssc_h", "ssc_w"),
                                   channel = c("pacific_blue_a"), method = c("earth"), 
                                   uptake = uptake.ff)
barcoded.ff <- cluster_fcbFlowFrame(barcoded.ff, channel = c("pacific_blue_a"), levels = 8, opt = "mixture", dist = "Skew.normal")
barcoded.ff <- assign_fcbFlowFrame(barcoded.ff, channel = c("pacific_blue_a") , likelihoodcut = 8, ambiguitycut = 0.05)
##------------------------------------------------------------------------------
barcoded.ff <- deskew_fcbFlowFrame(barcoded.ff, ret.model = T, predictors = c("fsc_a","ssc_a"),# "fsc_h", "fsc_w", "ssc_h", "ssc_w"),
                                   channel = c("pacific_orange_a"), method = c("earth"), 
                                   uptake = uptake.ff)
barcoded.ff <- cluster_fcbFlowFrame(barcoded.ff, channel = c("pacific_orange_a"), levels = 6, opt = "mixture", dist = "Skew.normal")
barcoded.ff <- assign_fcbFlowFrame(barcoded.ff, channel = c("pacific_orange_a") , likelihoodcut = 8, ambiguitycut = 0.05)
##------------------------------------------------------------------------------
myassignments <- getAssignments(barcoded.ff)
barcoded.fs <- split(barcoded.ff, myassignments) 
barcoded.fs2 <- apply_platemap(barcoded.fs, myplatemap, prefix = "truth")
##------------------------------------------------------------------------------
ggcyto::ggcyto(barcoded.fs2, aes(x = `Pacific Orange-A`, y = `Pacific Blue-A`)) + 
  geom_bin2d(bins = 128) + 
  scale_fill_viridis_c(option = "A") + 
  facet_wrap(~well)
```

```{r minimal sequential workflow}
##------------------------------------------------------------------------------
barcoded.ff <- deskew_fcbFlowFrame(barcoded.ff, ret.model = T, predictors = c("fsc_a","ssc_a"),# "fsc_h", "fsc_w", "ssc_h", "ssc_w"),
                                   channel = c("pacific_blue_a"), method = c("earth"), 
                                   uptake = uptake.ff)
barcoded.ff <- cluster_fcbFlowFrame(barcoded.ff, channel = c("pacific_blue_a"), levels = 8, opt = "mixture", dist = "Skew.normal", 
                                    subsample = 1e3)
barcoded.ff <- assign_fcbFlowFrame(barcoded.ff, channel = c("pacific_blue_a") , likelihoodcut = 8, ambiguitycut = 0.05)
####----------------------------------------------------------------------------
myassignments <- getAssignments(barcoded.ff)
barcoded.fs <- split(barcoded.ff, myassignments) 
##------------------------------------------------------------------------------
class(barcoded.fs)
barcoded.fs <- deskew_fcbFlowSet(barcoded.fs, ret.model = T, predictors = c("fsc_a","ssc_a"),# "fsc_h", "fsc_w", "ssc_h", "ssc_w"),
                                   channel = c("pacific_orange_a"), method = c("earth"), 
                                   uptake = uptake.ff)
barcoded.fs <- cluster_fcbFlowSet(barcoded.fs, channel = c("pacific_orange_a"), levels = 6, opt = "mixture", dist = "Skew.normal", 
                                  subsample = 1e3)
barcoded.fs <- assign_fcbFlowSet(barcoded.fs, channel = c("pacific_orange_a") , likelihoodcut = 8, ambiguitycut = 0.05)
##------------------------------------------------------------------------------
myassignments <- getAssignments(barcoded.ff)
barcoded.fs <- split(barcoded.ff, myassignments) 
barcoded.fs2 <- apply_platemap(barcoded.fs, myplatemap, prefix = "truth")
##------------------------------------------------------------------------------
ggcyto::ggcyto(barcoded.fs2, aes(x = `Pacific Orange-A`, y = `Pacific Blue-A`)) + 
  geom_bin2d(bins = 128) + 
  scale_fill_viridis_c(option = "A") + 
  facet_wrap(~well)
```

